services:
  nginx:
    image: nginx:alpine
    ports:
      - "2052:80"
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/wwwroot:/usr/share/nginx/html:ro
    depends_on:
    restart: always
      - apiserver
    
  apiserver:
    build:
      context: ./ApiServer
      dockerfile: Dockerfile
    container_name: web-apiserver
    ports:
      - "5000:5000"
    volumes:
      - ./ApiServer/.sec:/app/.sec:ro
    environment:
      - DOTNET_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    expose:
      - "5000"
    restart: always
